In [1]:
import numpy as np
import pandas as pd

In [32]:
dataset = pd.read_csv('accounts_payable_v2_complete_adapted.csv')
dataset.shape

(261934, 6)

In [33]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 261934 entries, 0 to 261933
Data columns (total 6 columns):
 #   Column               Non-Null Count   Dtype  
---  ------               --------------   -----  
 0   company_seller_name  261934 non-null  object 
 1   doc_emission_date    261934 non-null  object 
 2   total_value          261934 non-null  float64
 3   tag                  116569 non-null  object 
 4   category             261934 non-null  object 
 5   id_document          261934 non-null  object 
dtypes: float64(1), object(5)
memory usage: 12.0+ MB


In [4]:
import random
to_stay = random.sample(dataset['category'].unique().tolist(), 8)
dataset = dataset[dataset.category.isin(to_stay)]
dataset.shape

(5571, 6)

In [5]:
len(dataset['category'].unique())

8

In [6]:
dataset['company_seller_name'] = dataset['company_seller_name'].apply(lambda c: c.replace(" ",""))
dataset.head()

company_seller_name doc_emission_date  total_value  \
140       FEDERALEXPRESSCORPORATION        2014-11-20         7.14   
156                 KWASSOCIATESINC        2014-11-26        54.70   
204  BOULDERCOUNTYFINANCIALSERVICES        2014-12-10         5.63   
206  BOULDERCOUNTYFINANCIALSERVICES        2014-12-10         9.98   
207  BOULDERCOUNTYFINANCIALSERVICES        2014-12-10        11.15   

                   tag                     category id_document  
140                NaN  Capital: Bldgs & Bldg Equip   FT 000140  
156  Jantar Natal 2020      Printing & Binding Fees   FT 000156  
204                NaN      Printing & Binding Fees   FT 000204  
206  Jantar Natal 2020      Printing & Binding Fees   FT 000206  
207                NaN      Printing & Binding Fees   FT 000207

In [7]:
dataset['doc_emission_date'] = pd.to_datetime(dataset['doc_emission_date']).astype(int)/ 10**9
dataset.head()

company_seller_name  doc_emission_date  total_value  \
140       FEDERALEXPRESSCORPORATION       1.416442e+09         7.14   
156                 KWASSOCIATESINC       1.416960e+09        54.70   
204  BOULDERCOUNTYFINANCIALSERVICES       1.418170e+09         5.63   
206  BOULDERCOUNTYFINANCIALSERVICES       1.418170e+09         9.98   
207  BOULDERCOUNTYFINANCIALSERVICES       1.418170e+09        11.15   

                   tag                     category id_document  
140                NaN  Capital: Bldgs & Bldg Equip   FT 000140  
156  Jantar Natal 2020      Printing & Binding Fees   FT 000156  
204                NaN      Printing & Binding Fees   FT 000204  
206  Jantar Natal 2020      Printing & Binding Fees   FT 000206  
207                NaN      Printing & Binding Fees   FT 000207

In [7]:
dataset.shape

(3163, 6)

In [8]:
dataset.head()

company_seller_name  doc_emission_date  total_value  \
286  TOSHIBAAMERICABUSINESSSOLUTIONS,INC       1.419293e+09       100.51   
333  TOSHIBAAMERICABUSINESSSOLUTIONS,INC       1.419725e+09       235.14   
387            CANONSOLUTIONSAMERICA,INC       1.419984e+09       185.72   
417                  LEWAN&ASSOCIATESINC       1.420070e+09        82.75   
420                  LEWAN&ASSOCIATESINC       1.420070e+09        82.75   

               tag                   category id_document  
286            NaN  Copy Charges and Supplies   FT 000286  
333            NaN  Copy Charges and Supplies   FT 000333  
387            NaN  Copy Charges and Supplies   FT 000387  
417  Despesas Com1  Copy Charges and Supplies   FT 000417  
420            NaN  Copy Charges and Supplies   FT 000420

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidfconverter = TfidfVectorizer(max_features=1500, min_df=5, max_df=0.7, stop_words='english')
X1 = tfidfconverter.fit_transform(dataset['company_seller_name']).toarray()

In [10]:
X1.shape

(3163, 47)

In [11]:
X = pd.DataFrame(X1)
X['value'] = dataset['total_value'].values
X['date'] = dataset['doc_emission_date'].values

In [12]:
X.head()

0    1    2    3    4    5    6    7         8    9  ...   39   40   41  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  ...  0.0  0.0  0.0   
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  ...  0.0  0.0  0.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  ...  0.0  0.0  0.0   
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.707107  0.0  ...  0.0  0.0  0.0   
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.707107  0.0  ...  0.0  0.0  0.0   

    42   43   44   45   46   value          date  
0  0.0  0.0  1.0  0.0  0.0  100.51  1.419293e+09  
1  0.0  0.0  1.0  0.0  0.0  235.14  1.419725e+09  
2  0.0  0.0  0.0  0.0  0.0  185.72  1.419984e+09  
3  0.0  0.0  0.0  0.0  0.0   82.75  1.420070e+09  
4  0.0  0.0  0.0  0.0  0.0   82.75  1.420070e+09  

[5 rows x 49 columns]

In [13]:
dataset['category'] = dataset['category'].astype('category')
dataset["category_id"] = dataset["category"].cat.codes
dataset.head()

company_seller_name  doc_emission_date  total_value  \
286  TOSHIBAAMERICABUSINESSSOLUTIONS,INC       1.419293e+09       100.51   
333  TOSHIBAAMERICABUSINESSSOLUTIONS,INC       1.419725e+09       235.14   
387            CANONSOLUTIONSAMERICA,INC       1.419984e+09       185.72   
417                  LEWAN&ASSOCIATESINC       1.420070e+09        82.75   
420                  LEWAN&ASSOCIATESINC       1.420070e+09        82.75   

               tag                   category id_document  category_id  
286            NaN  Copy Charges and Supplies   FT 000286            1  
333            NaN  Copy Charges and Supplies   FT 000333            1  
387            NaN  Copy Charges and Supplies   FT 000387            1  
417  Despesas Com1  Copy Charges and Supplies   FT 000417            1  
420            NaN  Copy Charges and Supplies   FT 000420            1

In [111]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

X_train, X_test, y_train, y_test = train_test_split(X, dataset['category_id'], test_size=0.2, random_state=0)

In [103]:
from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier(n_neighbors=len(dataset['category_id'].unique()))

In [104]:
classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=8)

In [105]:
y_pred = classifier.predict(X_test)

In [109]:
#print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
#print(accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         7
           1       0.32      0.18      0.23       101
           2       0.00      0.00      0.00         7
           3       0.82      0.92      0.87      1483
           4       0.14      0.06      0.08       109
           5       0.00      0.00      0.00         4
           6       0.64      0.59      0.62       651
           7       0.00      0.00      0.00         4

    accuracy                           0.75      2366
   macro avg       0.24      0.22      0.22      2366
weighted avg       0.71      0.75      0.73      2366



In [12]:
from sklearn.ensemble import RandomForestClassifier
import random
from sklearn.feature_extraction.text import TfidfVectorizer

random.seed = 0

dataset = pd.read_csv('accounts_payable_v2_complete_adapted.csv')
dataset['company_seller_name'] = dataset['company_seller_name'].apply(lambda c: c.replace(" ",""))
dataset['doc_emission_date'] = pd.to_datetime(dataset['doc_emission_date']).astype(int)/ 10**9
dataset['category'] = dataset['category'].astype('category')
dataset["category_id"] = dataset["category"].cat.codes

to_stay = random.sample(dataset['category'].unique().tolist(), 8)
new_dataset = dataset[dataset.category.isin(to_stay)]

tfidfconverter = TfidfVectorizer(max_features=1500, min_df=5, max_df=0.7, stop_words='english')
X1 = tfidfconverter.fit_transform(new_dataset['company_seller_name']).toarray()
X = pd.DataFrame(X1)
X['value'] = new_dataset['total_value'].values
X['date'] = new_dataset['doc_emission_date'].values

results = rndforest_gridsearch(X, new_dataset['category_id'])

model = results.best_estimator_

tmp = new_dataset.head(1)
print(tmp)

n_d = pd.DataFrame(tfidfconverter.transform(tmp['company_seller_name']).toarray())
print(n_d.head())
n_d['value'] = tmp['total_value'].values
n_d['date'] = tmp['doc_emission_date'].values

cat = model.predict(n_d)
print(cat)

Fitting 3 folds for each of 4 candidates, totalling 12 fits


/Users/pimonteiro/repos/ml-data-analytics/env/lib/python3.8/site-packages/sklearn/model_selection/_split.py:670: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(("The least populated class in y has only %d"
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  12 out of  12 | elapsed:    3.0s finished


0.7268011527377523
RandomForestClassifier(criterion='entropy')
{'criterion': 'entropy', 'n_estimators': 100}
       company_seller_name  doc_emission_date  total_value            tag  \
76  KLEEN-TECHSERVICESCORP       1.412035e+09      3773.79  Despesas Com2   

                         category id_document  category_id  
76  Janitorial and Custodial Svcs   FT 000076          152  
   0    1    2    3    4    5    6    7    8    9    ...  98   99   100  101  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   

   102  103  104  105  106  107  
0  0.0  0.0  0.0  0.0  0.0  0.0  

[1 rows x 108 columns]
[152]


## GridSearch model

In [16]:
X_train = X
y_train = dataset['category_id']

In [8]:
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier

def kneares_gridsearch(X_train, y_train):
    params = {
        'n_neighbors': [3,5,1,19],
        'weights': ['uniform','distance'],
        'metric': ['euclidean','manhattan'],
        'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute']
    }
    
    gs = GridSearchCV(KNeighborsClassifier(), params, cv=3, n_jobs=-1, verbose=1)
    gs_results = gs.fit(X_train, y_train)
    print(gs_results.best_score_)
    print(gs_results.best_estimator_)
    print(gs_results.best_params_)
    
def svc_gridsearch(X_train, y_train):
    params = {
        'kernel': ['linear', 'poly', 'rbf', 'sigmoid', 'precomputed'],
        'C':[0.1, 1, 10],
        'gamma': ['auto'],
        'probability': [False]
    }
    
    gs = GridSearchCV(SVC(), params, cv=3, n_jobs=-1, verbose=1)
    gs_results = gs.fit(X_train, y_train)
    print(gs_results.best_score_)
    print(gs_results.best_estimator_)
    print(gs_results.best_params_)

def rndforest_gridsearch(X_train, y_train):
    params = {
        'n_estimators': [10, 100],
        'criterion': ['gini','entropy']
    }
    
    gs = GridSearchCV(RandomForestClassifier(), params, cv=3, n_jobs=-1, verbose=1)
    gs_results = gs.fit(X_train, y_train)
    print(gs_results.best_score_)
    print(gs_results.best_estimator_)
    print(gs_results.best_params_)
    return gs_results
    
def gradb_gridsearch(X_train, y_train):
    params = {
        'n_estimators': ['deviance', 'exponential'],
        'criterion': ['friedman_mse', 'mse'],
        'learning_rate': [0.01, 0.1, 1],
        'n_estimators': [10, 100]
    }
    
    gs = GridSearchCV(GradientBoostingClassifier(), params, cv=3, n_jobs=-1, verbose=1)
    gs_results = gs.fit(X_train, y_train)
    print(gs_results.best_score_)
    print(gs_results.best_estimator_)
    print(gs_results.best_params_)    

In [17]:
kneares_gridsearch()

Fitting 3 folds for each of 64 candidates, totalling 192 fits


/Users/pimonteiro/repos/ml-data-analytics/env/lib/python3.8/site-packages/sklearn/model_selection/_split.py:670: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=3.
  warnings.warn(("The least populated class in y has only %d"
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:    5.8s


0.21974183955802165
KNeighborsClassifier(metric='euclidean', n_neighbors=19)
{'algorithm': 'auto', 'metric': 'euclidean', 'n_neighbors': 19, 'weights': 'uniform'}


[Parallel(n_jobs=-1)]: Done 192 out of 192 | elapsed:   11.3s finished


In [126]:
svc_gridsearch()

Fitting 3 folds for each of 15 candidates, totalling 45 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.


KeyboardInterrupt: 

In [18]:
rndforest_gridsearch()

/Users/pimonteiro/repos/ml-data-analytics/env/lib/python3.8/site-packages/sklearn/model_selection/_split.py:670: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=3.
  warnings.warn(("The least populated class in y has only %d"
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.


Fitting 3 folds for each of 4 candidates, totalling 12 fits
0.8801460471055874
RandomForestClassifier(n_estimators=10)
{'criterion': 'gini', 'n_estimators': 10}


[Parallel(n_jobs=-1)]: Done  12 out of  12 | elapsed:    2.0s finished


In [25]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

X_train, X_test, y_train, y_test = train_test_split(X, dataset['category_id'], test_size=0.2, random_state=0)

In [26]:
model = RandomForestClassifier(criterion='gini', n_estimators=10)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[ 29   0   0   0   0   0]
 [  0 416   2   0   0   0]
 [  0   1 174   0   0   0]
 [  0   0   0   5   0   0]
 [  0   0   0   0   4   0]
 [  0   0   0   0   0   2]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        29
           1       1.00      1.00      1.00       418
           2       0.99      0.99      0.99       175
           3       1.00      1.00      1.00         5
           4       1.00      1.00      1.00         4
           5       1.00      1.00      1.00         2

    accuracy                           1.00       633
   macro avg       1.00      1.00      1.00       633
weighted avg       1.00      1.00      1.00       633

0.995260663507109


In [46]:
def test_best_model(epochs):
    dataset = pd.read_csv('accounts_payable_v2_complete_adapted.csv')
    dataset['company_seller_name'] = dataset['company_seller_name'].apply(lambda c: c.replace(" ",""))
    dataset['doc_emission_date'] = pd.to_datetime(dataset['doc_emission_date']).astype(int)/ 10**9
    dataset['category'] = dataset['category'].astype('category')
    dataset["category_id"] = dataset["category"].cat.codes
    
    for i in range(epochs):
        to_stay = random.sample(dataset['category'].unique().tolist(), 8)
        new_dataset = dataset[dataset.category.isin(to_stay)]
        
        tfidfconverter = TfidfVectorizer(max_features=1500, min_df=5, max_df=0.7, stop_words='english')
        X1 = tfidfconverter.fit_transform(new_dataset['company_seller_name']).toarray()
        X = pd.DataFrame(X1)
        X['value'] = new_dataset['total_value'].values
        X['date'] = new_dataset['doc_emission_date'].values
        
        print("=====Iteration ",i,"=====")
        rndforest_gridsearch(X, new_dataset['category_id'])
        #kneares_gridsearch(X, new_dataset['category_id'])
        gradb_gridsearch(X, new_dataset['category_id'])


In [44]:
gradb_gridsearch(X_train, y_train)

Fitting 3 folds for each of 12 candidates, totalling 36 fits


/Users/pimonteiro/repos/ml-data-analytics/env/lib/python3.8/site-packages/sklearn/model_selection/_split.py:670: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=3.
  warnings.warn(("The least populated class in y has only %d"
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  36 out of  36 | elapsed:   34.3s finished


0.9897234731147129
GradientBoostingClassifier()
{'criterion': 'friedman_mse', 'learning_rate': 0.1, 'n_estimators': 100}


In [48]:
test_best_model(5)

=====Iteration  0 =====
Fitting 3 folds for each of 4 candidates, totalling 12 fits


/Users/pimonteiro/repos/ml-data-analytics/env/lib/python3.8/site-packages/sklearn/model_selection/_split.py:670: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=3.
  warnings.warn(("The least populated class in y has only %d"
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  12 out of  12 | elapsed:    7.4s finished


0.583735781720015
RandomForestClassifier(criterion='entropy', n_estimators=10)
{'criterion': 'entropy', 'n_estimators': 10}
Fitting 3 folds for each of 12 candidates, totalling 36 fits


/Users/pimonteiro/repos/ml-data-analytics/env/lib/python3.8/site-packages/sklearn/model_selection/_split.py:670: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=3.
  warnings.warn(("The least populated class in y has only %d"
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  36 out of  36 | elapsed:  1.1min finished


0.5333586433323135
GradientBoostingClassifier(learning_rate=0.01, n_estimators=10)
{'criterion': 'friedman_mse', 'learning_rate': 0.01, 'n_estimators': 10}
=====Iteration  1 =====
Fitting 3 folds for each of 4 candidates, totalling 12 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  12 out of  12 | elapsed:    6.7s finished


0.6316618535048569
RandomForestClassifier(criterion='entropy')
{'criterion': 'entropy', 'n_estimators': 100}
Fitting 3 folds for each of 12 candidates, totalling 36 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  36 out of  36 | elapsed:  4.4min finished


0.7198739826726174
GradientBoostingClassifier(learning_rate=0.01, n_estimators=10)
{'criterion': 'friedman_mse', 'learning_rate': 0.01, 'n_estimators': 10}
=====Iteration  2 =====
Fitting 3 folds for each of 4 candidates, totalling 12 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  12 out of  12 | elapsed:    1.8s finished


0.9974593495934959
RandomForestClassifier(criterion='entropy')
{'criterion': 'entropy', 'n_estimators': 100}
Fitting 3 folds for each of 12 candidates, totalling 36 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  36 out of  36 | elapsed:   31.9s finished


0.9949186991869919
GradientBoostingClassifier()
{'criterion': 'friedman_mse', 'learning_rate': 0.1, 'n_estimators': 100}
=====Iteration  3 =====
Fitting 3 folds for each of 4 candidates, totalling 12 fits


/Users/pimonteiro/repos/ml-data-analytics/env/lib/python3.8/site-packages/sklearn/model_selection/_split.py:670: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(("The least populated class in y has only %d"
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  12 out of  12 | elapsed:    3.3s finished


0.6708742402992053
RandomForestClassifier(criterion='entropy')
{'criterion': 'entropy', 'n_estimators': 100}
Fitting 3 folds for each of 12 candidates, totalling 36 fits


/Users/pimonteiro/repos/ml-data-analytics/env/lib/python3.8/site-packages/sklearn/model_selection/_split.py:670: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(("The least populated class in y has only %d"
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  36 out of  36 | elapsed:  1.3min finished


0.5935016362786348
GradientBoostingClassifier(criterion='mse', learning_rate=0.01, n_estimators=10)
{'criterion': 'mse', 'learning_rate': 0.01, 'n_estimators': 10}
=====Iteration  4 =====
Fitting 3 folds for each of 4 candidates, totalling 12 fits


/Users/pimonteiro/repos/ml-data-analytics/env/lib/python3.8/site-packages/sklearn/model_selection/_split.py:670: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=3.
  warnings.warn(("The least populated class in y has only %d"
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  12 out of  12 | elapsed:    1.3s finished


0.972326569136385
RandomForestClassifier(criterion='entropy')
{'criterion': 'entropy', 'n_estimators': 100}
Fitting 3 folds for each of 12 candidates, totalling 36 fits


/Users/pimonteiro/repos/ml-data-analytics/env/lib/python3.8/site-packages/sklearn/model_selection/_split.py:670: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=3.
  warnings.warn(("The least populated class in y has only %d"
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  36 out of  36 | elapsed:   15.4s finished


0.9549189869435267
GradientBoostingClassifier(criterion='mse')
{'criterion': 'mse', 'learning_rate': 0.1, 'n_estimators': 100}


In [47]:
model = GradientBoostingClassifier()
model.fit(X_train, y_train, verbose=1)

y_pred = model.predict(X_test)

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

TypeError: fit() got an unexpected keyword argument 'verbose'

In [32]:
results = rndforest_gridsearch(X_train, y_train)

Fitting 3 folds for each of 4 candidates, totalling 12 fits


/Users/pimonteiro/repos/ml-data-analytics/env/lib/python3.8/site-packages/sklearn/model_selection/_split.py:670: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=3.
  warnings.warn(("The least populated class in y has only %d"
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  12 out of  12 | elapsed:    5.8s finished


In [37]:
from sklearn import tree

final = results.best_estimator_


In [55]:
from datetime import datetime, timedelta

expiration = datetime.now() + timedelta(days = 15)
print(expiration)

2021-01-06 19:30:16.793971


In [26]:
tr = "{\"0\":{\"nif\":\"1234\",\"company_seller_name\":\"Razoes para Adultos\",\"total_value\":130,\"doc_emission_date\":\"2020-12-22\"},\"1\":{\"nif\":\"1234\",\"company_seller_name\":\"Razoes para Adultos\",\"total_value\":130,\"doc_emission_date\":\"2020-12-22\"}}"
ttt = pd.read_json(tr, orient='index')
ttt

nif  company_seller_name  total_value doc_emission_date
0  1234  Razoes para Adultos          130        2020-12-22
1  1234  Razoes para Adultos          130        2020-12-22

In [35]:
type(ttt['nif'][0])

str

In [31]:
ttt['nif'] = ttt.nif.astype(str)
ttt.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2 entries, 0 to 1
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   nif                  2 non-null      object
 1   company_seller_name  2 non-null      object
 2   total_value          2 non-null      int64 
 3   doc_emission_date    2 non-null      object
dtypes: int64(1), object(3)
memory usage: 80.0+ bytes


In [25]:
results = {}
categories = [130, 130]
for i in range(len(categories)):
    results[i] = categories[i]

results

{0: 130, 1: 130}

In [28]:
import json
p = {
    "0": {
     "nif":"1234",
     "company_seller_name":"Razoes para Adultos",
     "total_value":130,
     "doc_emission_date": "2020-12-22"
    },
        "1": {
     "nif":"1234",
     "company_seller_name":"Razoes para Adultos",
     "total_value":130,
     "doc_emission_date": "2020-12-22"
    }
}

json.dumps(p)

'{"0": {"nif": "1234", "company_seller_name": "Razoes para Adultos", "total_value": 130, "doc_emission_date": "2020-12-22"}, "1": {"nif": "1234", "company_seller_name": "Razoes para Adultos", "total_value": 130, "doc_emission_date": "2020-12-22"}}'